# Generated by Django 3.1.4 on 2021-04-10 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matter',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classe',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.level'),
        ),
        migrations.AddField(
            model_name='classe',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_class', to='school.speciality'),
        ),
    ]
