# Generated by Django 3.2 on 2021-04-29 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20210412_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('describe', models.TextField()),
                ('limit_day', models.DateField()),
                ('course_day', models.DateField()),
                ('begin_time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matter_program', to='school.matter')),
            ],
        ),
    ]
