# Generated by Django 3.2 on 2021-05-28 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_question_reponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecon',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_lecon', to='school.program', unique=True),
        ),
    ]
