# Generated by Django 3.1.4 on 2021-04-11 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210411_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='start_date',
            new_name='create_at',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='role',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_user', to='users.roles'),
        ),
    ]
