# Generated by Django 3.1.4 on 2021-04-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210411_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='born_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
